import {
  AllocatorAllocatedPayload,
  AllocatorFailedPayload,
  AllocatorRequestedPayload,
  CostCeilingUnenforceablePayload,
  CostCeilingUnreachablePayload,
  CostCreditRateUnknownPayload,
  CostGenerationIdMissingPayload,
  CostFailedPayload,
  CostManagedMeteringSkippedPayload,
  CostNotionalUnpricedPayload,
  CostOverageUnobservablePayload,
  CostProviderCaptureFailedPayload,
  CostReconcileFailedPayload,
  CostResolvedPayload,
  CostRouteUnmeterablePayload,
  CostUnattributedPayload,
  CredentialConfiguredPayload,
  CredentialFailedPayload,
  CredentialGithubConfiguredPayload,
  CredentialLoadedPayload,
  CredentialRequestedPayload,
  CredentialScopedTokenMintedPayload,
  ReleaseFinalizedPayload,
  RunnerAllocatedPayload,
  RunnerFailedPayload,
  RunnerReleasedPayload,
  RunnerSweptPayload,
  UsageAccountingFailedPayload,
  UsageAccountingObservedPayload,
  UsageReadFailedPayload,
  UsageTokenAccountingFailedPayload,
  UsageWindowObservedPayload,
  UsageWindowPressurePayload,
  WorkspaceBootstrapDeferredPayload,
  WorkspaceFailedPayload,
  WorkspaceGitCapturedPayload,
  WorkspacePreparedPayload,
} from "./infra.js";

export const infrastructureEventRegistry = {
  "runner.allocated": RunnerAllocatedPayload,
  "runner.released": RunnerReleasedPayload,
  "runner.swept": RunnerSweptPayload,
  "release.finalized": ReleaseFinalizedPayload,
  "runner.failed": RunnerFailedPayload,
  "allocator.requested": AllocatorRequestedPayload,
  "allocator.allocated": AllocatorAllocatedPayload,
  "allocator.failed": AllocatorFailedPayload,
  "workspace.prepared": WorkspacePreparedPayload,
  "workspace.git_captured": WorkspaceGitCapturedPayload,
  "workspace.failed": WorkspaceFailedPayload,
  "workspace.bootstrap_deferred": WorkspaceBootstrapDeferredPayload,
  "credential.requested": CredentialRequestedPayload,
  "credential.loaded": CredentialLoadedPayload,
  "credential.failed": CredentialFailedPayload,
  "credential.configured": CredentialConfiguredPayload,
  "credential.github.configured": CredentialGithubConfiguredPayload,
  "credential.scoped_token_minted": CredentialScopedTokenMintedPayload,
  "cost.resolved": CostResolvedPayload,
  "cost.failed": CostFailedPayload,
  "cost.unattributed": CostUnattributedPayload,
  "cost.ceiling_unreachable": CostCeilingUnreachablePayload,
  "cost.ceiling_unenforceable": CostCeilingUnenforceablePayload,
  "cost.route_unmeterable": CostRouteUnmeterablePayload,
  "cost.generation_id_missing": CostGenerationIdMissingPayload,
  "cost.credit_rate_unknown": CostCreditRateUnknownPayload,
  "cost.overage_unobservable": CostOverageUnobservablePayload,
  "cost.managed_metering_skipped": CostManagedMeteringSkippedPayload,
  "cost.provider_capture_failed": CostProviderCaptureFailedPayload,
  "cost.notional_unpriced": CostNotionalUnpricedPayload,
  "cost.reconcile_failed": CostReconcileFailedPayload,
  "usage.window.observed": UsageWindowObservedPayload,
  "usage.window.pressure": UsageWindowPressurePayload,
  "usage.accounting.observed": UsageAccountingObservedPayload,
  "usage.read_failed": UsageReadFailedPayload,
  "usage.token_accounting_failed": UsageTokenAccountingFailedPayload,
  "usage.accounting_failed": UsageAccountingFailedPayload,
} as const;
